Завершение работ
htmlacademy-ecmascript/1236041-cinemaddict-12 pull request #10
Opened 2020-08-31 23:20 UTC by SampetovaN

2020-09-01 20:25 UTC, AlexMasterov commented on src/presenter/films-board.js
> +    }
https://github.com/htmlacademy-ecmascript/1236041-cinemaddict-12/blob/448bc73532010696a8e058ea63e02c7ce65e34eb/src/presenter/films-board.js#L114

<details>
<summary>_renderShowMoreButton</summary>

https://github.com/htmlacademy-ecmascript/1236041-cinemaddict-12/blob/448bc73532010696a8e058ea63e02c7ce65e34eb/src/presenter/films-board.js#L110-L112
</details>

Нужно удалить всё условие с проверкой и установкой `null`.

2020-09-01 20:29 UTC, AlexMasterov commented on src/presenter/films-board.js
> +    }
https://github.com/htmlacademy-ecmascript/1236041-cinemaddict-12/blob/448bc73532010696a8e058ea63e02c7ce65e34eb/src/presenter/films-board.js#L83
<details>
<summary>_renderSort</summary>

https://github.com/htmlacademy-ecmascript/1236041-cinemaddict-12/blob/448bc73532010696a8e058ea63e02c7ce65e34eb/src/presenter/films-board.js#L79-L81
</details>

Нужно удалить всё условие с проверкой и установкой `null`.

2020-09-01 20:31 UTC, AlexMasterov commented on src/presenter/films-board.js
> +    const filteredFilms = filter[filterType](films);
https://github.com/htmlacademy-ecmascript/1236041-cinemaddict-12/blob/448bc73532010696a8e058ea63e02c7ce65e34eb/src/presenter/films-board.js#L50

`.slice` не нужен, ведь `filter` уже возвращает новый массив.

2020-09-01 20:35 UTC, AlexMasterov commented on src/presenter/filter.js
> +    return [
<details>
<summary>filters</summary>

https://github.com/htmlacademy-ecmascript/1236041-cinemaddict-12/blob/448bc73532010696a8e058ea63e02c7ce65e34eb/src/presenter/filter.js#L58
https://github.com/htmlacademy-ecmascript/1236041-cinemaddict-12/blob/448bc73532010696a8e058ea63e02c7ce65e34eb/src/presenter/filter.js#L62
https://github.com/htmlacademy-ecmascript/1236041-cinemaddict-12/blob/448bc73532010696a8e058ea63e02c7ce65e34eb/src/presenter/filter.js#L67
https://github.com/htmlacademy-ecmascript/1236041-cinemaddict-12/blob/448bc73532010696a8e058ea63e02c7ce65e34eb/src/presenter/filter.js#L72
</details>

Б5~

2020-09-01 20:36 UTC, AlexMasterov commented on src/presenter/filter.js
> +class Filter {
<details>
<summary>Filter</summary>

https://github.com/htmlacademy-ecmascript/1236041-cinemaddict-12/blob/448bc73532010696a8e058ea63e02c7ce65e34eb/src/presenter/filter.js#L8-L9
https://github.com/htmlacademy-ecmascript/1236041-cinemaddict-12/blob/448bc73532010696a8e058ea63e02c7ce65e34eb/src/presenter/filter.js#L11
https://github.com/htmlacademy-ecmascript/1236041-cinemaddict-12/blob/448bc73532010696a8e058ea63e02c7ce65e34eb/src/presenter/filter.js#L13
</details>

Д3

<details>
<summary>Покажи пример исправления</summary>

```diff
- this._filterModel = filterModel;
+ this._model = filterModel;
```

```diff
- this._filterComponent = null;
+ this._view = null;
```
</details>

2020-09-01 20:44 UTC, AlexMasterov commented on src/presenter/film-card.js
> +    if (document.contains(prevFullComponent.element)) {
https://github.com/htmlacademy-ecmascript/1236041-cinemaddict-12/blob/448bc73532010696a8e058ea63e02c7ce65e34eb/src/presenter/film-card.js#L55

```diff
- if (document.contains(prevFullComponent.element)) {
+ if (document.body.contains(prevFullComponent.element)) {
```

2020-09-01 20:47 UTC, AlexMasterov commented on src/utils/const.js
> +export {TIME_MARKS, FilmListTitleOption, SortType, WatchingDateYearRange, MonthRange, DAY_DATE, UserAction, UpdateType, FilterType, COMMENT_AUTHORS};
<details>
<summary>utils/const.js</summary>

https://github.com/htmlacademy-ecmascript/1236041-cinemaddict-12/blob/448bc73532010696a8e058ea63e02c7ce65e34eb/src/utils/const.js#L1-L4
</details>

Перенеси сразу в `mock/const.js`.

2020-09-01 20:48 UTC, AlexMasterov commented on src/utils/const.js
> +const COMMENT_AUTHORS = [`Tim Macoveev`, `John Doe`, `Peter Parker`, `Alice Cooper`, `Tamara Green`];
`COMMENT_AUTHORS` нужно удалить.

2020-09-01 21:06 UTC, AlexMasterov requested changes

2020-09-01 21:06 UTC, AlexMasterov commented on src/main.js
<details>
<summary>utils/const.js</summary>

https://github.com/htmlacademy-ecmascript/1236041-cinemaddict-12/blob/448bc73532010696a8e058ea63e02c7ce65e34eb/src/utils/const.js#L5-L9
</details>

<details>
<summary>utils/utils.js</summary>

https://github.com/htmlacademy-ecmascript/1236041-cinemaddict-12/blob/448bc73532010696a8e058ea63e02c7ce65e34eb/src/utils/utils.js#L23-L30
</details>

Перенеси сразу в `mock/random.js` или `mock/film-card.js`.

> Скоро удалим

2020-09-01 21:08 UTC, AlexMasterov requested changes

2020-09-01 21:08 UTC, AlexMasterov commented on src/main.js
<details>
<summary>utils/utils.js</summary>

https://github.com/htmlacademy-ecmascript/1236041-cinemaddict-12/blob/448bc73532010696a8e058ea63e02c7ce65e34eb/src/utils/utils.js#L3
https://github.com/htmlacademy-ecmascript/1236041-cinemaddict-12/blob/448bc73532010696a8e058ea63e02c7ce65e34eb/src/utils/utils.js#L11-L21
https://github.com/htmlacademy-ecmascript/1236041-cinemaddict-12/blob/448bc73532010696a8e058ea63e02c7ce65e34eb/src/utils/utils.js#L32-L44
https://github.com/htmlacademy-ecmascript/1236041-cinemaddict-12/blob/448bc73532010696a8e058ea63e02c7ce65e34eb/src/utils/utils.js#L46-L51
</details>

Для работы с датой создай отдельный модуль `utils/date.js`.

2020-09-01 21:12 UTC, AlexMasterov requested changes

2020-09-01 21:12 UTC, AlexMasterov commented on src/presenter/films-board.js
>      this._filmsListTitleComponent = createFilmListTitleComponent;
<details>
<summary>factories/film-list-title.js</summary>

https://github.com/htmlacademy-ecmascript/1236041-cinemaddict-12/blob/448bc73532010696a8e058ea63e02c7ce65e34eb/src/factories/film-list-title.js#L1-L3
</details>

Модуль удали и пока снова создавай компонент через `new`.

2020-09-01 21:20 UTC, AlexMasterov requested changes

2020-09-01 21:20 UTC, AlexMasterov commented on src/view/film-card-full.js
> -import AbstractView from "./abstract.js";
<details>
<summary>view/abstract.js</summary>

https://github.com/htmlacademy-ecmascript/1236041-cinemaddict-12/blob/448bc73532010696a8e058ea63e02c7ce65e34eb/src/view/abstract.js#L18
</details>

```diff
- if (!this._element) {
+ if (this._element === null) { 
```

2020-09-01 21:20 UTC, AlexMasterov commented on src/main.js
<details>
<summary>view/film-card-full.js</summary>

https://github.com/htmlacademy-ecmascript/1236041-cinemaddict-12/blob/448bc73532010696a8e058ea63e02c7ce65e34eb/src/view/film-card-full.js#L10-L23
</details>

Перенеси в `utils/date.js`.

2020-09-01 21:24 UTC, AlexMasterov requested changes

2020-09-01 21:24 UTC, AlexMasterov commented on src/main.js
<details>
<summary>view/film-card.js</summary>

https://github.com/htmlacademy-ecmascript/1236041-cinemaddict-12/blob/448bc73532010696a8e058ea63e02c7ce65e34eb/src/view/film-card.js#L98
https://github.com/htmlacademy-ecmascript/1236041-cinemaddict-12/blob/448bc73532010696a8e058ea63e02c7ce65e34eb/src/view/film-card.js#L102
</details>

.film-card__controls-item--`mark-as-watched` !== this._`watched`ClickHandler
.film-card__controls-item--`add-to-watchlist` !== this._`watching`ClickHandler

Д4

2020-09-02 19:48 UTC, SampetovaN commented on src/presenter/films-board.js
> +    const filteredFilms = filter[filterType](films);
да, вот с этим какая-то проблема вышла. если убираю slice, то новый массив для дефолтного списка не возращается. долго сидела, но так и не доехала, почему список не обновляется... подумала, что проблема в функции sortFilms

2020-09-02 20:25 UTC, SampetovaN commented on src/view/film-card-full.js
> +      id: nanoid(),
так если я сейчас удалю id, то я не смогу удалить комментарий. я же нахожу комментарий по id и его удаляю. Подскажи, пожалуйста, куда мне надо перенести временно формирование id?

2020-09-03 03:56 UTC, AlexMasterov commented on src/presenter/films-board.js
> +    const filteredFilms = filter[filterType](films);
> если убираю `slice`, то новый массив для **дефолтного списка** (= `FilterType.ALL`) не возращается

https://github.com/htmlacademy-ecmascript/1236041-cinemaddict-12/blob/7bba473303092918ce176cd235fe0dd5a50c23a1/src/utils/filter.js#L4

Обычно от функции фильтрации (наивно) ожидают, что новый массив вернется в любом случае, но здесь возвращается старый 😃

2020-09-03 06:30 UTC, AlexMasterov approved these changes

2020-09-03 06:31 UTC, AlexMasterov commented
Пожалуйста, посмотри чат и далее делай задание из раздела "Работа с сетью", чтобы естественным образом появилась долгожданная структура с комментариями 😃

На этом задание нет смысла задерживаться.

2020-09-03 06:35 UTC, AlexMasterov commented on src/view/film-card-full.js
> +      id: nanoid(),
Например, мне пришлось временно добавить модели `films` метод [`_deleteComment`](https://github.com/htmlacademy-ecmascript/1236041-cinemaddict-12/blob/7bba473303092918ce176cd235fe0dd5a50c23a1/src/view/film-card-full.js#L269-L281).

Не советую 😄
Предлагаю скорее реализовать получения данных с сервера.

2020-09-03 06:38 UTC, merged